version: '3.9'

services:

  #new service (app)
  track_app:
    container_name: track_app
    image: track9/app:${ENV}
    build: .
    ports:
      - "${DOCKER_PORT}:8080"
    env_file:
      - ./.env
      - ./secrets.env
      - ./var.env
    depends_on:
      - track_db
    command: >
      sh -c "
      ./mvnw flyway:repair &&
      ./mvnw flyway:migrate &&
      ./mvnw spring-boot:run
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


  #old service (postgres)

  track_db:
    container_name: track_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Commented as this code below is not working. I wanted to avoid the default credentials.. But it is not working.  
    # user: "postgres"
    # command: >
    #   bash -c "
    #   postgres -D /var/lib/postgresql/data &
    #   sleep 5 &&
    #   psql -U postgres -tc \"SELECT 1 FROM pg_roles WHERE rolname='track'\" | grep -q 1 || psql -U postgres -c \"CREATE USER track WITH PASSWORD 'trackdb';\" &&
    #   psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE postgres TO track;\" &&
    #   fg
    #   "
volumes:
  pgdata: {}