version: '3.9'

services:

  #new service (app)
  track_app:
    container_name: track_app
    image: track9/app:${ENV}
    build: .
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - ./.env
      - ./var.env
    depends_on:
      - track_db
    volumes:
      - ./app/files:/files
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


  #old service (postgres)

  track_db:
    container_name: track_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}