ALTER TABLE courses ADD COLUMN content VARCHAR(8000);
ALTER TABLE subjects ADD COLUMN content VARCHAR(8000);
ALTER TABLE modules ADD COLUMN content VARCHAR(8000);
ALTER TABLE topics ADD COLUMN content VARCHAR(8000);
ALTER TABLE units ADD COLUMN content VARCHAR(8000);